#!/bin/bash
#  ----------------------------------------------------------------
#  unpack the CPC archive.  Install a .desktop file
#  ----------------------------------------------------------------
echo start postinst 32043df4
echo during Postinst, pwd is `pwd`

#The filename changes frequently.
#if [ ! -e /opt/CPC/distr/BlackBox-2302-core.7z ] 
#then
#	mkdir -p /opt/CPC/distr
#	pushd  /opt/CPC/distr
#	wget	http://www.zinnamturm.eu/pac/BlackBox-2302-core.7z
#	popd
#fi

pushd /opt/CPC
  7za x distr/BlackBox-2302-core.7z
mkdir -p lib/Extras/{Code,Docu,Mod,Rsrc}
popd

mkdir -p /usr/local/share/applications
ln -s /opt/CPC/share/applications/CPC.desktop 	/usr/local/share/applications/CPC.desktop

#  ----------------------------------------------------------------
#  display information during install.  Pre-Depends: wine is set in
#  the control file, but this fails if wine is not previously installed.
#  ----------------------------------------------------------------
mkdir -p /tmp/cpc/32043df4
cd /tmp/cpc/32043df4
env WINEPREFIX=/tmp/cpc/32043df4/.wine wine /opt/CPC/lib/BlackBox.exe /O /opt/CPC/doc/SetupAutostart.odc /USE . &

df /opt
echo finish postinst 32043df4

