#!/bin/bash
#  ----------------------------------------------------------------
#  unpack the CPC archive.  Install a .desktop file
#  ----------------------------------------------------------------
echo start postinst 4a5a651a
echo during Postinst, pwd is `pwd`

#The filename changes frequently.
#if [ ! -e /opt/cpc/distr/BlackBox-2302-core.7z ] 
#then
#	mkdir -p /opt/cpc/distr
#	pushd  /opt/cpc/distr
#	wget	http://www.zinnamturm.eu/pac/BlackBox-2302-core.7z
#	popd
#fi

pushd /opt/cpc
  7za x distr/BlackBox-2302-core.7z
mkdir -p lib/Extras/{Code,Docu,Mod,Rsrc}
popd

mkdir -p /usr/local/share/applications
ln -s /opt/cpc/share/applications/cpc.desktop 	/usr/local/share/applications/cpc.desktop

#  ----------------------------------------------------------------
#  display information during install.  Pre-Depends: wine is set in
#  the control file, but this fails if wine is not previously installed.
#  ----------------------------------------------------------------
chgrp -R adm /opt/cpc
chmod -R g+w /opt/cpc

mkdir -p /tmp/cpc/4a5a651a
cd /opt/cpc/etc
env WINEPREFIX=/tmp/cpc/4a5a651a/.wine wine /opt/cpc/lib/BlackBox.exe /USE . &


df /opt
echo finish postinst 4a5a651a

