#!/bin/bash
#  ----------------------------------------------------------------
#  unpack the CPC archive.  Install a .desktop file
#  ----------------------------------------------------------------
echo start postinst 05236e14
echo during Postinst, pwd is `pwd`

#The filename changes frequently.
#if [ ! -e /opt/cpc/distr/BlackBox-2302-core.7z ] 
#then
#	mkdir -p /opt/cpc/distr
#	pushd  /opt/cpc/distr
#	wget	http://www.zinnamturm.eu/pac/BlackBox-2302-core.7z
#	popd
#fi

pushd /opt/cpc
  7za x distr/BlackBox-2302-core.7z
popd

mkdir -p /usr/local/share/applications
ln -s /opt/cpc/share/applications/cpc.desktop 	/usr/local/share/applications/cpc.desktop

#  ----------------------------------------------------------------
#  Pre-Depends: wine 
#  is set in the control file, but this fails if wine is not 
#  previously installed.
#  ----------------------------------------------------------------
chgrp -R cpc /opt/cpc
chmod -R g+w /opt/cpc/lib/.

mkdir -p /tmp/cpc/05236e14
cd /opt/cpc/etc

# su cpc #was denied
env WINEPREFIX=/tmp/cpc/05236e14/.wine wine /opt/cpc/lib/BlackBox.exe /USE . &


df /opt
echo finish postinst 05236e14

