#!/bin/bash
#  ----------------------------------------------------------------
#  Announces itself
#  ----------------------------------------------------------------
echo start postrm 05236e14.  The action is ${action}
echo 
if [ "$action" = "purge" ] ; then
	deluser cpc
fi

echo finish postrm 05236e14

