#!/bin/bash
#  ----------------------------------------------------------------
#  re-arm /opt/template0/deb; n.b. cp omits .git
#  ----------------------------------------------------------------
echo start postrm e9a77bc3
echo finish postrm e9a77bc3

