#!/bin/bash
#  ----------------------------------------------------------------
#  re-arm /opt/template0/deb; n.b. cp omits .git
#  ----------------------------------------------------------------
echo start postrm 32043df4
echo finish postrm 32043df4

