#!/bin/bash
#  ----------------------------------------------------------------
#  The /opt directory exists on exit.  Display available space.
#  ----------------------------------------------------------------
echo start preinst 32043df4
mkdir -p /opt
df /opt
echo finish preinst 32043df4

