#!/bin/bash
#  ----------------------------------------------------------------
#  remove files created by postinst
#  ----------------------------------------------------------------
echo start prerm 4a5a651a

if [ -d /opt/cpc/BlackBox-2302-core ] 
then 
	rm -r /opt/cpc/BlackBox-2302-core
fi

if [ -f /usr/local/share/applications/cpc.desktop ] 
then 
	rm -r /usr/local/share/applications/cpc.desktop
fi

echo finish prerm 4a5a651a

