#!/bin/bash
#  ----------------------------------------------------------------
#  remove files created by postinst
#  ----------------------------------------------------------------
echo start prerm 32043df4

if [ -d /opt/CPC/BlackBox-2302-core ] 
then 
	rm -r /opt/CPC/BlackBox-2302-core
fi

if [ -f /usr/local/share/applications/CPC.desktop ] 
then 
	rm -r /usr/local/share/applications/CPC.desktop
fi

echo finish prerm 32043df4

