#!/bin/bash
#  ----------------------------------------------------------------
#  re-arm /opt/template0/deb; n.b. cp omits .git
#  ----------------------------------------------------------------
echo start prerm 32043df4
echo finish prerm 32043df4

